Repository CombatClassifieds/Website, pull requests merged in 2024-02, with the labels that each got.

#8 integration with tailwind
  client/app.css
  client/package.json
  client/postcss.config.js
  client/tailwind.config.js
  package-lock.json
Labels: enhancement, REDACTED

#15 Footer
  client/components/Footer.jsx
  client/footer.css
  client/index.html
  client/tailwind.config.js
Labels: REDACTED

#17 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: REDACTED

#21 Update README.md
  README.md
Labels: documentation

#16 creating github action
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/node.js.yml
  client/app.css
  client/components/App.jsx
  client/components/Content.jsx
  client/components/Footer.jsx
  client/components/Header.jsx
  client/footer.css
  client/postcss.config.js
  client/tailwind.config.js
Labels: enhancement

#24 static assets proof-of-concept
  client/components/Header.jsx
  client/public/images/logo.jpeg
Labels: bug

#20 Footer
  client/components/Footer.jsx
  client/footer.css
Labels: enhancement

#26 GitHub pages
  .github/workflows/node.js.yml
  client/vite.config.js
Labels: enhancement, REDACTED, dev-ops

#30 fixing image
  client/components/Header.jsx
Labels: bug

#36 using font-awesome
  README.md
  client/components/Footer.jsx
  client/components/Header.jsx
  client/package.json
  package-lock.json
Labels: enhancement, REDACTED

#42 Video bg
  client/components/Footer.jsx
  client/footer.css
  client/public/videos/motivation.mp4
Labels: enhancement, REDACTED

#41 Content Page
  client/1itemdetails.css
  client/app.css
  client/components/App.jsx
  client/components/Content.jsx
  client/components/Footer.jsx
  client/index.html
  client/public/images/futuristic_secret_tank.jpeg
  client/public/images/glasses.jpeg
  client/public/images/lego_secret_tank.jpeg
  client/public/images/logo.jpeg
  client/public/images/secret_weapon.jpeg
  client/public/images/spyplane.jpeg
Labels: REDACTED

#43 Added some content and working buttons
  client/1itemdetails.css
  client/app.css
  client/components/App.jsx
  client/components/Content.jsx
  client/components/Header.jsx
  client/public/images/thermalBG.jpeg
Labels: enhancement

#45 Added Spacing and Borders
  client/app.css
Labels: enhancement

#52 Merged w button hover. Added hover effects and pointer
  README.md
  client/1sideScroll.css
  client/app.css
  client/components/App.jsx
  client/components/Content.jsx
  package-lock.json
  package.json
Labels: documentation, enhancement

#54 styled buttons added to each image
  client/1sideScroll.css
  client/components/App.jsx
  client/components/Content.jsx
Labels: enhancement, REDACTED

#53 added hover yellow to header elements
  client/app.css
  client/components/Header.jsx
Labels: enhancement, REDACTED

#57 Docker
  .dockerignore
  .eslintrc.json
  .github/workflows/node.js.yml
  .gitignore
  .prettierignore
  Dockerfile
  README.md
  client/1itemdetails.css
  client/1sideScroll.css
  client/app.css
  client/components/App.jsx
  client/components/Content.jsx
  client/index.html
  client/index.jsx
  client/package.json
  client/tailwind.config.js
  client/vite.config.js
  docker-compose.yml
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  public/fonts/Bootcamp-Morsecode.otf
  public/images/futuristic_secret_tank.jpeg
  public/images/glasses.jpeg
  public/images/lego_secret_tank.jpeg
  public/images/logo.png
  public/images/secret_weapon.jpeg
  public/images/spyplane.jpeg
  public/images/thermalBG.jpeg
  public/videos/motivation.mp4
  server/migration.sql
  server/package.json
  server/server.js
  sql/seed.sql
  src/app/_content/Content.jsx
  src/app/_content/content.css
  src/app/_footer/Footer.jsx
  src/app/_footer/footer.css
  src/app/_header/Header.jsx
  src/app/_header/header.css
  src/app/api/categories/route.js
  src/app/api/items/[id]/route.js
  src/app/api/popular_brands/route.js
  src/app/api/subcategories/[id]/route.js
  src/app/favicon.ico
  src/app/foo/page.js
  src/app/globals.css
  src/app/item/[id]/page.css
  src/app/item/[id]/page.js
  src/app/layout.js
  src/app/page.js
  src/app/template.js
  src/db.js
  tailwind.config.js
Labels: REDACTED

#58 added readMe info
  README.md
  sql/seed.sql
  temp.env.local
Labels: documentation, REDACTED

#61 specifying text color
  src/app/_header/header.css
Labels: enhancement

#62 Readme
  DEVOPS.md
  README.md
  sql/seed.sql
Labels: documentation

#64 Seed data
  DEVOPS.md
  sql/faker.js
Labels: documentation, enhancement
